<?php

namespace AppBundle\Repository;

/**
 * CardRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function getRandom()
    {
        $array =   $this->createQueryBuilder('a')
            ->from('AppBundle:Card', 'c')
            ->where('c.cardvalue < :maxvalue')
            ->setParameter('maxvalue', 1000)
            ->getQuery()->getResult();
        shuffle($array);
        return($array[0]);
    }
}
