app:
    resource: '@AppBundle/Controller/'
    type: annotation
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_user_registration_confirmed:
                path: /
                defaults:
                    _controller: FrameworkBundle:Redirect:urlRedirect
                    path: /